name = "cf_b2b_shop"
main = "src/index.js"
compatibility_date = "2026-07-08"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "b2b_shop_db"
database_id = "7588223f-bf24-48de-ab6a-f8009d506e49"

# Environment variables
[vars]
ENVIRONMENT = "development"

# R2 Storage for images
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "b2b-product-images"

[[kv_namespaces]]
binding = "POSTER_STORE" #
id = "a46fb54666694d72b296a5b73eac6b5c" # 从 Cloudflare 获取的 KV Namespace ID